services:
  db:
    image: mysql:8.0
    container_name: mysql_django
    restart: unless-stopped
    env_file: .env
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - ./.docker/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_USER_PASSWORD}
